theme: minima
title: Test Blog
author: CupOKyle
email: kyleforsythcomedy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning how GitHub Pages works. I want to become very good at working with open source projects.

# social links
twitter_username: cupokyle # DO NOT include the @ character, or else the build will fail!
github_username:  cupokyle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
